### ISSUE TITLE
P09-1 (v2.0) sk.22: trūksta pirmo skliausto 𝜣𝟎 apibrėžime (skaidrės)

### ISSUE THREAD

**Issue by ugnegaiz** [mokymai/taisymai-2020#165]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** skaidrės
3. **Skaidrių bloko pavadinimas ir versija:** P09-1 v2.0 
4. **Skaidrės numeris:** 
5. **Glaustai aprašykite netikslumą:** skyrybos klaida

6.  **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** 𝜣𝟎 galimų parametro reikšmių, kai H0 teisinga) 
7. **Netikslumo tekstas:** 𝜣𝟎 galimų parametro
8. **Siūlomas taisymo tekstas:** 𝜣𝟎 (galimų parametro
9. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

![Screenshot (107)](https://user-images.githubusercontent.com/71369697/99839144-e862fe80-2b72-11eb-8a1e-e77448ae0e4c.png)

Patvirtinkite pažymėdami [x]:

- [ ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Dublikatas #160
