### ISSUE TITLE
biostatistika: tikimybė patekti į GA → tikimybė patekti į imtį (loginė klaida)

### ISSUE THREAD

**Issue by ievasokolovaite** [mokymai/taisymai-2020#177]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/tyrimu-planavimas.html
4. **Glaustai aprašykite netikslumą:**  loginė klaida

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  imant antrą elementą, GA nariams yra didesnė tikimybė patekti į GA, nei imant pirmą 
6. **Netikslumo tekstas:** tikimybė patekti į GA
7. **Siūlomas taisymo tekstas:** tikimybė patekti į imtį
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
![Untitled](https://user-images.githubusercontent.com/71064213/103475005-0ba7dd00-4db2-11eb-8775-ae27a9d1dffd.png)

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Labai vertinga pastaba, dėkui.
