### ISSUE TITLE
biostatistika: statistai → statistikai (loginė klaida)

### ISSUE THREAD

**Issue by kairys-m** [mokymai/taisymai-2020#180]
1. **Kursas:** Biostatistika (BS-2020)
2. **Netikslumo vieta:** svetainė (teorija)
3. **Nuoroda (URL):** https://mokymai.github.io/biostatistika/tyrimu-eiga.html
4. **Glaustai aprašykite netikslumą:**  loginė klaida, netinkamai pavartotas žodis, nes pagal https://www.lietuviuzodynas.lt/terminai/Statistas žodžio "Statistas" reikšmė yra: Statistas - (it. statista): 1. nedidelio vaidmens be žodžių atlikėjas; 2.prk. neveiklus, nereikšmingas ko nors dalyvis.

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:**  Modelį sukūrė statistai R.J. MaKay 
6. **Netikslumo tekstas:** statistai
7. **Siūlomas taisymo tekstas:** statistikai
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.
<img width="805" alt="Screenshot 2021-01-04 at 10 42 19" src="https://user-images.githubusercontent.com/71021865/103516677-94d61700-4e79-11eb-9934-794a8a36be09.png">

Patvirtinkite pažymėdami [x]:

- [x] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Labai gera pastaba.
