### ISSUE TITLE
programa-r: neveikia nuoroda į DataCamp

### ISSUE THREAD

**Issue by Bernadeta-Al** [mokymai/taisymai-2020#186]
1. **Kursas:** Įvadas į duomenų analizę programa R (R-2020)
2. **Netikslumo vieta:** svetainė (pratybos)
3. **Nuoroda (URL):** https://mokymai.github.io/r-2020-v/s07.html#funkcija-ggplot 
4. **Glaustai aprašykite netikslumą:**  Neveikia nuoroda į DataCamp kurso video

5. **Nukopijuokite netikslumą su keliais žodžiais aplinkui:** ... 
6. **Netikslumo tekstas:** ...
7. **Siūlomas taisymo tekstas:** ...
8. **Ekrano nuotrauka („Screenshots“)** su pažymėta netikslumo vieta.

<img width="899" alt="Screenshot_6" src="https://user-images.githubusercontent.com/60813811/105488280-0acfe000-5cba-11eb-9168-bc962d451083.png">

Patvirtinkite pažymėdami [x]:

- [x ] Apie šią problemą dar niekas nėra pranešęs. Aš esu pirmasis/pirmoji.
- [ x] Pateikiau informatyvų temos pavadinimą, pagal kurį galima identifikuoti problemos esmę.
- [ x] Formą užpildžiau tinkamai.

**Comment by GegznaV** [comment]
Bandykite jungtis tiesiai per _DataCamp_ kursą apie _ggplot2_, nes jie kartais  pakeičia nuorodas.

**Comment by GegznaV** [comment]
Markdown labai jautrus tarpų buvimui/nebuvimui:
![image](https://user-images.githubusercontent.com/12725868/105497051-01994000-5cc7-11eb-86e8-1f4cb2d4df49.png)

**Comment by GegznaV** [comment]
Dabar turėtų veikti
